version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: dev_portfolio_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data